### ISSUE TITLE
Mosparo verification doesn't load if form is in Elementor popup

### ISSUE THREAD

**Issue by Sapper-Morton** [mosparo/wordpress-plugin#11]
Title says it. If I have a form with mosparo inside Elementor popup the script fails to load.

![image](https://github.com/mosparo/wordpress-plugin/assets/23439320/638ca62f-5377-4560-94a3-303112c4464a)

**Comment by zepich** [comment]
Hi @Sapper-Morton 

Thank you very much for the issue.

Can you share a screenshot how you configured it in Elementor so I can try to test it with the similar setup?

Thank you very much!

Kind regards,

zepich

**Comment by Sapper-Morton** [comment]
Its a basic Elementor popup. There's a button in footer which triggers it when pressed.

<img width="1228" alt="image" src="https://github.com/mosparo/wordpress-plugin/assets/23439320/a2bbf0ea-971d-43c3-9680-cc63b75a2415">

**Comment by zepich** [comment]
Hi @Sapper-Morton 

Thank you very much for your details.

I was able to create a popup and reproduce the issue. I know the problem, and I'm working on fixing it. I found a fix already, but I'm not 100% happy with it. I will investigate and test it and probably release a fix tomorrow evening.

The problem is that Elementor adds the popup code to the DOM, and mosparo gets initialized, but Elementor then removes the HTML structure until it opens the popup again. mosparo, on the other hand, tries to initialize the mosparo box during the page load but then gets interrupted.

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @Sapper-Morton 

I've just released v1.9.1 of the WordPress plugin.

This contains the fix for the popup issue.

Can you have a look and let me know if it's working correctly with your popup?

Thank you very much!

Kind regards,

zepich

**Comment by Sapper-Morton** [comment]
Thank you so much. I'll check it tomorrow!

**Comment by zepich** [comment]
Perfect! You're welcome! :)
