### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by Jensdnl** [mosparo/wordpress-plugin#6]
Hello, I really appreciate this plugin. However, our website does not utilize jQuery, and the plugin is currently loading the entire jQuery library. Could you kindly remove the jQuery dependency and instead use vanilla JS? (ChatGPT is adept at rewriting jQuery code). Thank you!

**Comment by zepich** [comment]
Hi @Jensdnl 

Thank you very much for bringing this issue to our attention!

I honestly didn't remember that we used jQuery. I can't even remember why we required jQuery. We developed the frontend JavaScript of mosparo with VanillaJS, and it's ridiculous to use jQuery for these lines in the WordPress plugin. I wonder why we didn't use VanillaJS directly.

We will adjust it right away. But it will take a moment (probably 2 - 3 weeks) to adjust, test, and release the new version (1.9). 

Thank you very much for your feedback. Have a nice day!

Kind regards,

zepich

**Comment by Jensdnl** [comment]
> Hi @Jensdnl 
> 
> 
> 
> Thank you very much for bringing this issue to our attention!
> 
> 
> 
> I honestly didn't remember that we used jQuery. I can't even remember why we required jQuery. We developed the frontend JavaScript of mosparo with VanillaJS, and it's ridiculous to use jQuery for these lines in the WordPress plugin. I wonder why we didn't use VanillaJS directly.
> 
> 
> 
> We will adjust it right away. But it will take a moment (probably 2 - 3 weeks) to adjust, test, and release the new version (1.9). 
> 
> 
> 
> Thank you very much for your feedback. Have a nice day!
> 
> 
> 
> Kind regards,
> 
> 
> 
> zepich

Thank you, Zepich! If you need any help, let me know!

**Comment by zepich** [comment]
Hi @Jensdnl 

We've just released the new version v1.9, in which we switched to Vanilla JS as discussed.

The modules for Ninja Forms, Elementor Form, and Everest Forms still have the dependency on jQuery, but this is because these plugins have the dependency already, so we do not add another dependency with mosparo, and switching that code to Vanilla JS makes a bigger mess then solving anything (in my eyes).

I will close this issue now.

Kind regards,

zepich
