### ISSUE TITLE
Label editable 

### ISSUE THREAD

**Issue by Jensdnl** [mosparo/wordpress-plugin#7]
Hallo Zepich,

It would be very helpful if we could change the label text. For example, we also have newsletter input fields and calls to action that only have one field. The Mosparo text is too long in this case, see:

<img width="316" alt="Scherm­afbeelding 2024-03-22 om 09 35 54" src="https://github.com/mosparo/wordpress-plugin/assets/69464780/ff7ae8ad-d35b-46d5-a8bc-76acb7d12688">

**Comment by zepich** [comment]
Hi @Jensdnl 

You mean the sentence "Ik ga ermee akkoord dat....", right?

It's already possible to adjust the label. You can specify the labels in the frontend box's initialization script (See here: https://documentation.mosparo.io/docs/integration/custom/#custom-messages). 

To do that in the WordPress plugin, you can use a filter: `mosparo_integration_filter_frontend_options` (See here: 
https://github.com/mosparo/wordpress-plugin/blob/master/src/MosparoIntegration/Helper/FrontendHelper.php#L111)

#### Example:

```php
function mosparoOverrideMessages($options)
{
    $options['customMessages'] = [
        'de' => [
            'label' => 'Ich akzeptiere',
        ],
        'en' => [
            'label' => 'I accept',
        ],
    ];

    return $options;
}
add_filter('mosparo_integration_filter_frontend_options', 'mosparoOverrideMessages');
```

I recommend using this with the option `language` so you can specify exactly which language should be used. Otherwise, some users would see the box in their browser language (and still the long text) and not with your added (short) translation.

#### Example:

```php
function mosparoOverrideMessages($options)
{
    $options['language'] = 'de_DE'; // Replace with your language, you can also use functions like `pll_current_language()` for example
    $options['customMessages'] = [
        'de' => [
            'label' => 'Ich akzeptiere',
        ],
        'en' => [
            'label' => 'I accept',
        ],
    ];

    return $options;
}
add_filter('mosparo_integration_filter_frontend_options', 'mosparoOverrideMessages');
```

Additionally, you could also use the invisible mode (see here: https://documentation.mosparo.io/docs/usage/settings#invisible-mode) for these short forms (or in general) so that the user does not have to click this extra box.

Do these options fulfill your requirements, or do you need more options? I'm looking forward to your feedback.

Kind regards,

zepich

**Comment by Jensdnl** [comment]
Hello Zapich, thank you so much for your prompt response. It was incredibly helpful!

Your last suggestion (invisible mode) is indeed the most suitable for these short forms. I'm not entirely sure how to activate this on the Wordpress website. Is there a filter for this as well?

**Comment by zepich** [comment]
Hi @Jensdnl 

Thank you for your feedback!

You have to enable this feature in the design settings of the mosparo project (in the mosparo interface). It's impossible to enable this feature in WordPress directly because the CSS file from mosparo is adjusted for the invisible mode.

If you want to use the visible and invisible modes in forms on the same website, you must create two projects in mosparo. You can then add both projects as connections to your WordPress site. In the mosparo field in your forms, you can then define which connection should be used.

Please let me know if you need more information or have more questions.

Have a nice day!

Kind regards,

zepich

**Comment by Jensdnl** [comment]
@zepich That's clear. Thank you very much!
